on:
  push:
    branches:
      - main
env:
  NODE_VERSION: "20"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install and test
        run: |
          # Install and test if it is available
          npm ci
      - name: Build angular
        run: |
          # Build for develop environment
          npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEANDRO_DEV_2D04F }}
          channelId: live
          projectId: leandro-dev-2d04f
